import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {VM,JavaFault,signature} from '../dist/vm.js';import {MIDP} from '../dist/midp.js';import {parseMidi} from '../dist/midi.js';
function run(code,ret='I',exceptions=[]){const method={access:8,name:'test',desc:'()'+ret,code,locals:4,exceptions};const vm=new VM({Test:{name:'Test',super:'java/lang/Object',fields:[],methods:[method],cp:[],interfaces:[]}},{clock:()=>0});const t=vm.start(null,'test','()'+ret,[],'Test');vm.tick(0,1000);assert.equal(vm.errors.length,0);return t.result}
test('integer division follows signed Java truncation',()=>assert.equal(run([17,255,249,6,108,172]),-2));
test('long stack category two survives dup2 and addition',()=>assert.equal(run([10,92,97,173],'J'),2n));
test('Java catch handler receives array bounds exception',()=>assert.equal(run([4,188,8,5,51,172,87,16,42,172],'I',[{start:0,end:6,handler:6,type:'java/lang/Exception'}]),42));
test('byte arrays preserve signed byte conversion',()=>assert.equal(run([4,188,8,89,3,17,0,255,84,3,51,172]),-1));
test('real descriptor argument parsing handles nested arrays and longs',()=>assert.deepEqual(signature('([[BILjava/lang/String;J)[[I'),{args:['[[B','I','Ljava/lang/String;','J'],ret:'[[I'}));
test('all original game classes and methods are present',()=>{const c=JSON.parse(fs.readFileSync(new URL('../dist/classes.json',import.meta.url)));assert.deepEqual(Object.keys(c).sort(),['a','b','c','d','e','f','tribes']);assert.equal(Object.values(c as Record<string, any>).reduce((n,x)=>n+x.methods.length,0),399);assert.equal(c.tribes.methods.some(m=>m.name==='startApp'),true)});
test('original MIDI parser preserves note timing and program',()=>{const bytes=Uint8Array.from([77,84,104,100,0,0,0,6,0,0,0,1,0,96,77,84,114,107,0,0,0,15,0,192,4,0,144,60,100,96,128,60,0,0,255,47,0]);const e:any[]=parseMidi(bytes) as any[];assert.equal(e[0].type,12);assert.equal(e[1].a,60);assert.equal(e[2].time,.5)});
